[general]

live_config_reload = true

[window]

opacity = 0.90
blur = true

padding.x = 10
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light"

dynamic_title = true

[font]

normal.family = "JetBrainsMono"
bold.family = "JetBrainsMono"
italic.family = "JetBrainsMono"
bold_italic.family = "JetBrainsMono"

size = 16.0

[selection]

save_to_clipboard = true

[mouse]

hide_when_typing = true

