---
- hosts: localhost
  tasks:
    - name: Set OS distribution dependent variables
      include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
      ignore_errors: yes

    - debug:
        var: ide_packages

    - name: Fail if distribution is not set
      fail:
        msg: "{{ ansible_facts['distribution'] }} distribution is not in the list" 
      when: os is undefined

    - name: Create Workspaces directory
      file:
        path: "{{ home_dir }}/{{ workspace_dir }}"
        state: directory

    - name: Install IDE
      block:
        - name: Get packages to install
          include_vars: "packages.yml"

        - debug:
            var: ide_packages

        - name: Install IDE packages
          shell: sudo -u {{ username }} yay --noconfirm -S {{ item }}
          with_items:
            - "{{ ide_packages }}"

        - name: Init IDE configurations
          include_tasks: "tasks/{{ item }}.yml"
          with_items:
            - "{{ ide_config }}"

    - name: Copy user local directory
      copy:
        src: .local/
        dest: "{{ home_dir }}/.local"
        directory_mode: yes
        remote_src: yes

