---
- hosts: localhost
  become: true
  tasks:
    - name: Set OS distribution dependent variables
      include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
      ignore_errors: yes

    - name: Fail if vars not set
      fail:
        msg: "{{ ansible_facts['distribution'] }} distribution is not in the list" 
      when: os is undefined

    - name: Get packages to install
      include_vars: "packages.yml"

    - debug:
        var: ide_packages

    - name: Install IDE tools
      shell: sudo -u {{ username }} yay --noconfirm -S {{ item }}
      with_items:
        - "{{ ide_packages }}"

    - name: setup vim
      include_tasks: "tasks/{{ item }}.yml"
      with_items:
        - "{{ ide_packages }}"

