---
- hosts: localhost
  become: true
  tasks:
    - name: Set OS distribution dependent variables
      include_vars: "os_{{ ansible_facts['distribution'] }}.yml"
      ignore_errors: yes

    - name: Fail if distribution is not set
      fail:
        msg: "{{ ansible_facts['distribution'] }} distribution is not in the list" 
      when: os is undefined

    - name: Create Workspaces directory
      file:
        path: "{{ home_dir }}/{{ workspace_dir }}"
        state: directory

    - name: Install IDE
      block:
        - debug:
            var: ide_packages

        - name: Install IDE packages
          shell: "sudo -u {{ username }} {{ install_command }} {{ item }}"
          with_items:
            - "{{ ide_packages }}"

        - name: Init IDE configurations
          include_tasks: "tasks/{{ item }}.yml"
          with_items:
            - "{{ ide_config }}"

        - name: Copy user local directory
          copy:
            src: .local/
            dest: "{{ home_dir }}/.local"
            directory_mode: yes
            remote_src: yes

        - name: Copy environment configuration
          copy:
            src: .env
            dest: "{{ home_dir }}/.env"
            remote_src: yes

        - name: Copy aliases
          copy:
            src: .aliases
            dest: "{{ home_dir }}/.aliases"
            remote_src: yes

        - name: Set default shell
          shell: "sudo usermod --shell /bin/{{ default_shell }} {{ username }}"
              
        - name: Set default keyboard layout using setxkbmap
          shell: "sudo -u {{ username }} setxkbmap -layout {{ default_keyboard }}"
      when: ide_install

    - name: Install system environment 
      block:
        - debug:
            var: system_packages

        - name: Install system packages
          shell: "sudo -u {{ username }} {{ install_command }} {{ item }}"
          with_items:
            - "{{ system_packages }}"

        - name: Init system configurations
          include_tasks: "tasks/{{ item }}.yml"
          with_items:
            - "{{ system_config }}"
      when: system_install

    - name: Install general packages 
      block:
        - debug:
            var: general_packages

        - name: Install system packages
          shell: "sudo -u {{ username }} {{ install_command }} {{ item }}"
          with_items:
            - "{{ general_packages }}"
      when: general_install
