---
- name: Create alacritty configuration directory
  file:
    path: "{{ home_dir }}/.config/alacritty"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Init alacritty configuration 
  copy:
    remote_src: yes
    src: .config/alacritty/alacritty.yml
    dest: "{{ home_dir }}/.config/alacritty/alacritty.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    backup: yes
