---
- name: Init bashrc
  copy:
    remote_src: yes
    src: .bashrc
    dest: "{{ home_dir }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'
    backup: yes

- name: Install bash configuration dependencies
  shell: "{{ install_command }} {{ bash_package }}"
  loop:
    - bash-completion
  loop_control:
    loop_var: bash_package
  become_user: "{{ username }}"

- name: Download bash starship installation
  get_url:
    url: https://starship.rs/install.sh
    dest: "/tmp/starship.sh"

- name: Run starship install script
  shell: "sh /tmp/starship.sh -y"
  register: starship_result
  ignore_errors: true
  become_user: "{{ username }}"
