---
- name: Init bashrc
  copy:
    remote_src: yes
    src: .bashrc
    dest: "{{ home_dir }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    backup: yes

- name: Install bash configuration dependencies
  shell: "sudo -u {{ username }} {{ install_command }} {{ bash_package }}"
  loop:
    - starship
    - bash-completion
  loop_control:
    loop_var: bash_package
