---
- name: Copy Dunst configurations
  copy:
    src: .config/dunst/
    dest: "{{ home_dir }}/.config/dunst/"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    mode: '0755'
    remote_src: yes

