---
- name: Download Source Code Pro font
  git:
    repo: https://github.com/adobe-fonts/source-code-pro
    dest: "/tmp/source-code-pro/"
    depth: 1

- name: Create font directory
  file:
    path: "{{ home_dir }}/.fonts"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    state: directory

- name: Copy source code pro font
  copy:
    src: "/tmp/source-code-pro/"
    dest: "{{ home_dir }}/.fonts/source-code-pro/"
    directory_mode: yes
    remote_src: yes

- name: Recursively change ownership of a directory
  file:
    path: "{{ home_dir }}/.fonts/source-code-pro"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'

- name: Update font cache
  shell: "fc-cache -f"
  become_user: "{{ username }}"
