--- 
- name: Add Global gitignore
  copy:
    remote_src: yes
    src: .gitignore
    dest: "{{ home_dir }}/.gitignore"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    backup: yes

- name: Add Global gitconfig
  copy:
    remote_src: yes
    src: .gitconfig
    dest: "{{ home_dir }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    backup: yes
