---
- name: Copy neofetch configurations
  copy:
    src: .config/neofetch/
    dest: "{{ home_dir }}/.config/neofetch/"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    mode: '0755'
    remote_src: yes

