---
- name: Add neovim plugins
  copy:
    remote_src: yes
    src: .config/nvim/plugins/plugins.vim
    dest: "{{ home_dir }}/.config/nvim/plugins/plugins.vim"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'
    backup: yes

- name: Install nvim-plug
  shell: "sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"
  become_user: "{{ username }}"

- name: Install neovim plugins
  shell: "nvim +PlugInstall! +qa!"
  args:
    stdin: "\n"
  become_user: "{{ username }}"

- name: Clean neovim plugins
  shell: "nvim +PlugClean! +qa!"
  args:
    stdin: "\n"
  become_user: "{{ username }}"
