---
- name: Copy nitrogen configuration
  copy:
    src: .config/nitrogen
    dest: "{{ home_dir }}/.config/nitrogen"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    mode: '0755'
    remote_src: yes
