---
- name: Download oh-my-zsh installation
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/tmp/ohmyzsh.sh"

- name: Set default shell value if not defined
  set_fact:
    default_shell: "{{ default_shell | default('') }}"
  when: default_shell is undefined

- name: Run oh-my-zsh install script
  shell: "KEEP_ZSHRC=yes CHSH={{ (default_shell == 'zsh' ) | ternary ('yes', 'no') }} sh /tmp/ohmyzsh.sh --unattended"
  register: ohmyzsh_result
  ignore_errors: true
  become_user: "{{ username }}"

- name: Check if oh-my-zsh is already installed
  debug:
    msg: "Oh-my-zsh is already installed"
  when: ohmyzsh_result.stdout == "The $ZSH folder already exists ({{ home_dir }}/.oh-my-zsh).\nYou'll need to remove it if you want to reinstall."

