---
- name: Install base-devel packages
  shell: sudo pacman -S --needed base-devel

- name: Remove paru repository if already exists
  file:
    state: absent
    path: "/tmp/paru"

- name: Clone paru repository
  git:
    repo: https://github.com/Morganamilo/paru
    dest: "/tmp/paru"

- name: Recursively change ownership of paru directory
  file:
    path: "/tmp/paru"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'

- name: Build paru
  shell:
    cmd: "makepkg -si"
    chdir: "/tmp/paru"
  become_user: "{{ username }}"
  register: paru_result
  ignore_errors: true

- name: Check if paru is already install
  debug:
    msg: "Paru is probably already installed"
  when: paru_result.rc != 0

