---
- name: Copy polybar configurations
  copy:
    src: .config/polybar/
    dest: "{{ home_dir }}/.config/polybar/"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    mode: '0755'
    remote_src: yes

