---
- name: Copy rofi configurations
  copy:
    src: .config/rofi/
    dest: "{{ home_dir }}/.config/rofi/"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    mode: '0755'
    remote_src: yes

