---
- name: Copy rofi configurations
  copy:
    src: .config/rofi/
    dest: "{{ home_dir }}/.config/rofi/"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    remote_src: yes

- name: Install tmux plugin manager
  git:
    repo: https://github.com/lr-tech/rofi-themes-collection.git
    dest: "/tmp/rofi-themes"



