---
- name: Install sddm themes and dependencies
  shell: "sudo -u {{ username }} {{ install_command }} {{ sddm_package }}"
  loop:
    - sddm-theme-sugar-candy-git
  loop_control:
    loop_var: sddm_package

- name: Copy i3wm configurations
  copy:
    src: /usr/lib/sddm/sddm.conf.d/default.conf
    dest: /etc/sddm.conf
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    directory_mode: yes
    mode: '0755'
    remote_src: yes

- name: Update theme of sddm
  replace:
    path: /etc/sddm.conf
    regexp: '^Current=$'
    replace: 'Current=Sugar-Candy'

- name: Update sddm sugar-candy theme
  copy:
    remote_src: yes
    src: sddm/theme.conf
    dest: "/usr/share/sddm/themes/Sugar-Candy/theme.conf"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'

- name: Disable display-manager to change it
  systemd:
    name: display-manager
    enabled: no

- name: Enable sddm as diplay-manager
  systemd:
    name: sddm
    enabled: yes

