---
- name: Install spotify configuration dependencies
  shell: "{{ install_command }} {{ spotify_package }}"
  loop:
    - spicetify-cli
    - spicetify-themes-git
  loop_control:
    loop_var: spotify_package
  become_user: "{{ username }}"

- name: Change permission to Spotify files
  shell: >
      chmod a+wr /opt/spotify ;
      chmod a+wr /opt/spotify/Apps -R ;

- name: Exec spotify to setup configuration
  shell: >
    spotify &
    sleep 5 ; killall -q spotify
  become_user: "{{ username }}"

- name: Init spicetify configuration
  shell: "spicetify"
  become_user: "{{ username }}"

- name: Enable spotify devtool
  shell: "spicetify backup apply enable-devtool ;"
  become_user: "{{ username }}"

- name: Get spicetify directory for Dribbblish
  shell: "echo $(dirname $(spicetify -c))/Themes/Dribbblish"
  register: spicetify_dir

- name: Create extensions directory
  file:
    path: "{{ spicetify_dir.stdout }}/../../Extensions"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    state: directory

- name: Enable spotify devtool
  copy:
    src: /usr/share/spicetify-cli/Themes/Dribbblish/dribbblish.js
    dest: "{{ spicetify_dir.stdout }}/../../Extensions/dribbblish.js"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    remote_src: yes

- name: Enable dribbblish extension
  shell: "spicetify config extensions {{ spicetify_dir.stdout }}/../../Extensions/dribbblish.js"
  become_user: "{{ username }}"

- name: Change theme and colorscheme
  shell: "spicetify config current_theme Dribbblish color_scheme nord-dark"
  become_user: "{{ username }}"
      
- name: Change css configuration
  shell: "spicetify config inject_css 1 replace_colors 1 overwrite_assets 1"
  become_user: "{{ username }}"

- name: Apply spicetify configuration
  shell: "spicetify apply"
  become_user: "{{ username }}"
