---
- name: Download bash starship installation
  get_url:
    url: https://starship.rs/install.sh
    dest: "/tmp/starship.sh"

- name: Run starship install script
  shell: "sh /tmp/starship.sh -y"
  register: starship_result
  ignore_errors: true
  become_user: "{{ username }}"

