---
- name: Init Tmux Conf
  copy:
    remote_src: yes
    src: .tmux.conf
    dest: "{{ home_dir }}/.tmux.conf"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'
    backup: yes

