---
- name: Create Workspaces directory
  file:
    path: "{{ home_dir }}/.tmux/plugins"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    state: directory
    mode: "0755"

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ home_dir }}/.tmux/plugins/tpm"

- name: Install Tmux plugins
  shell: "TMUX_PLUGIN_MANAGER_PATH={{ home_dir }}/.tmux/plugins/ {{ home_dir }}/.tmux/plugins/tpm/bin/install_plugins"

- name: Update Tmux plugins
  shell: "TMUX_PLUGIN_MANAGER_PATH={{ home_dir }}/.tmux/plugins/ {{ home_dir }}/.tmux/plugins/tpm/bin/update_plugins all"
    
- name: Clean Tmux plugins
  shell: "TMUX_PLUGIN_MANAGER_PATH={{ home_dir }}.tmux/plugins/ {{ home_dir }}/.tmux/plugins/tpm/bin/clean_plugins"

