---
- name: Create vim directory
  file:
    path: "{{ home_dir }}/.vim"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    state: directory

- name: Add vim plugins
  copy:
    remote_src: yes
    src: .vim/plugins.vim
    dest: "{{ home_dir }}/.vim/plugins.vim"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'
    backup: yes

- name: Create vim autoload directory
  file:
    path: "{{ home_dir }}/.vim/autoload/"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    state: directory

- name: Download plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home_dir }}/.vim/autoload/plug.vim"

- name: Install vim plugins
  shell: "vim +PlugInstall! +qa!"
  args:
    stdin: "\n"
  become_user: "{{ username }}"

- name: Clean vim plugins
  shell: "vim +PlugClean! +qa!"
  args:
    stdin: "\n"
  become_user: "{{ username }}"
