---
- name: Init vimrc
  copy:
    remote_src: yes
    src: .vimrc
    dest: "{{ home_dir }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    mode: '0755'
    backup: yes

