---
- name: Add vimrc to home dir
  copy:
    remote_src: yes
    src: .vimrc
    dest: /home/{{ username }}/.vimrc
    mode: '0644'
    backup: yes

- name: Init plugins  
  block:
    - name: Create vim directory
      file:
        path: /home/{{ username }}/.vim
        state: directory
    - name: Add vim plugins
      copy:
        remote_src: yes
        src: .vim/plugins.vim
        dest: /home/{{ username }}/.vim/plugins.vim
        mode: '0644'
        backup: yes

- name: Install junegunn/vim-plug
  block:
    - name: Create autoload directory
      file:
        path: /home/{{ username }}/.vim/autoload
        state: directory
    
    - name: Download plug.vim
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/{{ username }}/.vim/autoload/plug.vim

    - name: Run PlugInstall
      shell: "vim -c 'PlugInstall' -c 'qa!'"

