---
- name: Init zshrc
  copy:
    remote_src: yes
    src: .zshrc
    dest: "{{ home_dir }}/.zshrc"
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ group | default(username) }}"
    backup: yes

