---
- name: Init zshrc
  copy:
    remote_src: yes
    src: .zshrc
    dest: "{{ home_dir }}/.zshrc"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
    backup: yes


- name: Install oh-my-zsh 
  block:
    - name: Download oh-my-zsh installation
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/tmp/ohmyzsh.sh"

    - name: Run oh-my-zsh install script
      shell: "sudo -u {{ username }} KEEP_ZSHRC=yes CHSH={{ (default_shell == 'zsh' ) | ternary ('yes', 'no') }} sh /tmp/ohmyzsh.sh --unattended"
      register: ohmyzsh_result
      ignore_errors: true

    - name: Check if oh-my-zsh is already installed
      debug:
        msg: "Oh-my-zsh is already installed"
      when: ohmyzsh_result.stdout == "The $ZSH folder already exists ({{ home_dir }}/.oh-my-zsh).\nYou'll need to remove it if you want to reinstall."
  
