[main]
font = JetBrainsMono:size=10
prompt = 🌐 Profile >
lines = 10
width = 25
horizontal-pad = 12
vertical-pad = 12
inner-pad = 12
icon-theme = Papirus
anchor = bottom
 
[colors]
background = 0e141bff
text = e8f5e9ff
match = a8ff60ff
selection = 264d32ff
selection-text = ffffffff
selection-match = b4ff39ff
border = b4ff39ff
