# Format: /path/to/repo [branch] [--detailed-commits] [--noenv]

# Dotfiles
# /home/wabri/Workspaces/Github-Wabri/Personal/dotfiles/wt1

# SecondBrain
/home/wabri/Workspaces/Github-Wabri/Personal/SecondBrain/wt1
