### Global Variables
#
# Mod
#
  set $mod Mod4

# 
# Monitors
#
  set $laptopMonitor eDP-1
  set $upMonitor DP-9
  set $downMonitor DP-7

# 
# Directions
#
  set $left h
  set $down j
  set $up k
  set $right l

#
# Menu
#
  set $menu fuzzel
  set $awesome_menu vicinae toggle

# 
# File Manager
#
  set $fileManager nautilus

#
# Lockscreen
#
  set $screenlock 'swaylock --config $HOME/.config/swaylock/config'

# 
# Terminal Emulator
#
  set $term ghostty
  set $tmux-ide ghostty --title="tmux-ide" -e "tmux new -As local"

#
# Paths
#
  set $sway_scripts $HOME/.config/sway/scripts
