### Settings
#
# Output
#
  bindswitch --reload --locked lid:on output $laptopMonitor disable
  bindswitch --reload --locked lid:off output $laptopMonitor enable

  output $laptopMonitor pos 0 0 res 1920x1200
  output "Samsung Electric Company LU28R55 HNMW200331" pos 0 0 res 3840x2160
  output "Stargate Technology HDMI 0x00000022" pos 2560 2160 res 1920x1080

#
# Wallpaper
#
  output * bg ~/.config/sway/wallpaper.png fill
#
# Touchpad
#
  input "type:touchpad" {
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
    drag_lock disabled
  }
#
# Idle
#
  exec swayidle -w \
           timeout 900 $screenlock \
           timeout 960 'swaymsg "output * power off"' \
                resume 'swaymsg "output * power on"' \
           before-sleep $screenlock

