### Modes
#
# Resizing containers:
#
set $resize "↔️ Resize"
mode $resize {
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    # Exit resize mode menu
    bindsym Return exec makoctl dismiss --all; mode "default"
    bindsym Escape exec makoctl dismiss --all; mode "default"
    bindsym q exec makoctl dismiss --all; mode "default"
}
bindsym $mod+r exec notify-send $resize "h: Left, j: down, k: up, l: right"; mode $resize

#
# Screenshots
#
  set $screenshot "📸 Screenshot"
  mode $screenshot {
      # Full
      bindsym f exec $sway_scripts/screenshot-control.sh full; exec makoctl dismiss --all; mode "default"
      bindsym Ctrl+f exec $sway_scripts/screenshot-control.sh full --clipboard; exec makoctl dismiss --all; mode "default"
      # Selected window
      bindsym w exec $sway_scripts/screenshot-control.sh selected_window; exec makoctl dismiss --all; mode "default"
      bindsym Ctrl+w exec $sway_scripts/screenshot-control.sh selected_window --clipboard; exec makoctl dismiss --all; mode "default"
      # Selected area
      bindsym a exec $sway_scripts/screenshot-control.sh area; exec makoctl dismiss --all; mode "default"
      bindsym Ctrl+a exec $sway_scripts/screenshot-control.sh area --clipboard; exec makoctl dismiss --all; mode "default"
      # Focused window
      bindsym s exec $sway_scripts/screenshot-control.sh focused_window; exec makoctl dismiss --all; mode "default"
      bindsym Ctrl+s exec $sway_scripts/screenshot-control.sh focused_window --clipboard; exec makoctl dismiss --all; mode "default"
      # Focused output
      bindsym o exec $sway_scripts/screenshot-control.sh focused_output; exec makoctl dismiss --all; mode "default"
      bindsym Ctrl+o exec $sway_scripts/screenshot-control.sh focused_output --clipboard; exec makoctl dismiss --all; mode "default"

      # Exit screenshot mode menu
      bindsym Return exec makoctl dismiss --all; mode "default"
      bindsym Escape exec makoctl dismiss --all; mode "default"
      bindsym $mod+Print exec makoctl dismiss --all; mode "default"
  }
  bindsym Print exec notify-send $screenshot "F: Full, Ctrl+F: Full to clipboard,\nW: Select Window, Cltr+W: Select Window to clipboard,\nA: Select Area, Cltr+A: Select Area to clipboard,\nS: Focused Window, Cltr+S: Focused Window to clipboard,\nO: Focused Screen, Cltr+O: Focused Screen to clipboard"; mode $screenshot
  bindsym $mod+s exec notify-send $screenshot "F: Full, Ctrl+F: Full to clipboard,\nW: Select Window, Cltr+W: Select Window to clipboard,\nA: Select Area, Cltr+A: Select Area to clipboard,\nS: Focused Window, Cltr+S: Focused Window to clipboard,\nO: Focused Screen, Cltr+O: Focused Screen to clipboard"; mode $screenshot

# 
# Power
#
  set $mode_system "Power Mode"
  mode $mode_system {
      bindsym l exec $screenlock; exec makoctl dismiss --all; mode "default"
      bindsym o exec swaymsg exit; exec makoctl dismiss --all; mode "default"
      bindsym r exec systemctl reboot; exec makoctl dismiss --all; mode "default"
      bindsym s exec systemctl suspend; exec makoctl dismiss --all; mode "default"
      bindsym p exec systemctl poweroff; exec makoctl dismiss --all; mode "default"

      bindsym Return exec makoctl dismiss --all; mode "default"
      bindsym Escape exec makoctl dismiss --all; mode "default"
  }
  bindsym $mod+p exec notify-send "🔌 Power Mode" "L: Lock, S: Suspend, P: Poweroff, R: Reboot, O: Logout, Q: Cancel" --urgency=critical; mode $mode_system


