[main]
font = JetBrainsMono:size=18
lines = 6
prompt = 󰤆 Power >
width = 20
horizontal-pad = 12
vertical-pad = 12
inner-pad = 12
icon-theme = Papirus
anchor = top-right

[colors]
background = 0e141bff
text = e8f5e9ff
match = a8ff60ff
selection = 264d32ff
selection-text = ffffffff
selection-match = b4ff39ff
border = b4ff39ff
